-- =====================================================================
-- ABESDAC_Connect — Database Schema for Abeka SDA Church
-- Run this entire file in Supabase Studio → SQL Editor → New query.
-- This script is IDEMPOTENT: it is safe to paste and run more than
-- once (e.g. if a previous run errored partway through) without
-- causing "already exists" or "does not exist" errors.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. Extensions
-- ---------------------------------------------------------------------
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- 1. ENUM TYPES  (wrapped so re-running never errors on "already exists")
-- ---------------------------------------------------------------------
do $$ begin
  create type user_role as enum ('administrator', 'secretary', 'pastor', 'ministry_leader');
exception when duplicate_object then null; end $$;

do $$ begin
  create type member_status as enum ('active', 'inactive', 'archived', 'transferred', 'deceased');
exception when duplicate_object then null; end $$;

do $$ begin
  create type gender_type as enum ('male', 'female');
exception when duplicate_object then null; end $$;

do $$ begin
  create type marital_status_type as enum ('single', 'married', 'divorced', 'widowed');
exception when duplicate_object then null; end $$;

do $$ begin
  create type attendance_type as enum ('sabbath_service', 'midweek_service', 'event');
exception when duplicate_object then null; end $$;

do $$ begin
  create type event_status as enum ('upcoming', 'ongoing', 'completed', 'cancelled');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------
-- 2. PROFILES (extends Supabase auth.users)
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null,
  phone text,
  role user_role not null default 'secretary',
  avatar_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.profiles is 'App-level user profile + role, one row per auth.users row.';

-- ---------------------------------------------------------------------
-- 3. MINISTRIES
-- ---------------------------------------------------------------------
create table if not exists public.ministries (
  id uuid primary key default uuid_generate_v4(),
  name text not null unique,
  description text,
  leader_id uuid references public.profiles(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id)
);

-- ---------------------------------------------------------------------
-- 4. MEMBERS
-- ---------------------------------------------------------------------
create table if not exists public.members (
  id uuid primary key default uuid_generate_v4(),
  member_code text not null unique, -- e.g. ABK-0001, auto-generated by trigger below

  -- Personal information
  first_name text not null,
  last_name text not null,
  date_of_birth date,
  gender gender_type,
  marital_status marital_status_type,
  occupation text,
  nationality text,

  -- Contact information
  phone text,
  alternate_phone text,
  email text,
  residential_address text,
  gps_address text,

  -- Church information
  baptism_date date,
  date_joined date not null default current_date,
  district text,
  ministry_id uuid references public.ministries(id) on delete set null,
  status member_status not null default 'active',

  -- Family information
  spouse_name text,
  children_names text, -- comma-separated free text, kept simple for beginners
  emergency_contact_name text,
  emergency_contact_phone text,

  -- Media
  profile_image_url text,

  -- Meta
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id)
);

create index if not exists idx_members_name on public.members (last_name, first_name);
create index if not exists idx_members_status on public.members (status);
create index if not exists idx_members_ministry on public.members (ministry_id);
create index if not exists idx_members_archived on public.members (is_archived);

-- ---------------------------------------------------------------------
-- 5. MINISTRY_MEMBERS (join table)
-- ---------------------------------------------------------------------
create table if not exists public.ministry_members (
  id uuid primary key default uuid_generate_v4(),
  ministry_id uuid not null references public.ministries(id) on delete cascade,
  member_id uuid not null references public.members(id) on delete cascade,
  joined_at timestamptz not null default now(),
  unique (ministry_id, member_id)
);

-- ---------------------------------------------------------------------
-- 6. EVENTS
-- ---------------------------------------------------------------------
create table if not exists public.events (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  description text,
  location text,
  start_time timestamptz not null,
  end_time timestamptz,
  status event_status not null default 'upcoming',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id)
);

create index if not exists idx_events_start_time on public.events (start_time);

-- ---------------------------------------------------------------------
-- 7. ATTENDANCE
-- ---------------------------------------------------------------------
create table if not exists public.attendance (
  id uuid primary key default uuid_generate_v4(),
  member_id uuid not null references public.members(id) on delete cascade,
  attendance_type attendance_type not null,
  event_id uuid references public.events(id) on delete cascade, -- required only when attendance_type = 'event'
  service_date date not null default current_date,
  check_in_time timestamptz,
  check_out_time timestamptz,
  recorded_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  unique (member_id, attendance_type, event_id, service_date)
);

create index if not exists idx_attendance_member on public.attendance (member_id);
create index if not exists idx_attendance_date on public.attendance (service_date);

-- ---------------------------------------------------------------------
-- 8. ANNOUNCEMENTS
-- ---------------------------------------------------------------------
create table if not exists public.announcements (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  body text not null,
  is_pinned boolean not null default false,
  published_at timestamptz not null default now(),
  expires_at timestamptz,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 9. AUDIT LOGS
-- ---------------------------------------------------------------------
create table if not exists public.audit_logs (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references public.profiles(id) on delete set null,
  user_name text,
  action text not null,      -- e.g. 'create', 'update', 'delete', 'login'
  module text not null,      -- e.g. 'members', 'ministries', 'events', 'auth'
  record_id uuid,
  description text,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_created_at on public.audit_logs (created_at desc);
create index if not exists idx_audit_logs_module on public.audit_logs (module);

-- =====================================================================
-- 10. HELPER FUNCTIONS
-- =====================================================================

create or replace function public.current_role()
returns user_role
language sql
security definer
stable
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
as $$
  select coalesce((select role from public.profiles where id = auth.uid()) = 'administrator', false);
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.profiles (id, full_name, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    new.email,
    coalesce((new.raw_user_meta_data->>'role')::user_role, 'secretary')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();

drop trigger if exists trg_ministries_updated_at on public.ministries;
create trigger trg_ministries_updated_at before update on public.ministries for each row execute function public.set_updated_at();

drop trigger if exists trg_members_updated_at on public.members;
create trigger trg_members_updated_at before update on public.members for each row execute function public.set_updated_at();

drop trigger if exists trg_events_updated_at on public.events;
create trigger trg_events_updated_at before update on public.events for each row execute function public.set_updated_at();

drop trigger if exists trg_announcements_updated_at on public.announcements;
create trigger trg_announcements_updated_at before update on public.announcements for each row execute function public.set_updated_at();

-- Auto-generate member_code like ABK-0001
create sequence if not exists public.member_code_seq start 1;

create or replace function public.set_member_code()
returns trigger
language plpgsql
as $$
begin
  if new.member_code is null or new.member_code = '' then
    new.member_code := 'ABK-' || lpad(nextval('public.member_code_seq')::text, 4, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists trg_members_code on public.members;
create trigger trg_members_code before insert on public.members for each row execute function public.set_member_code();

create or replace function public.write_audit_log()
returns trigger
language plpgsql
security definer
as $$
declare
  actor uuid := auth.uid();
  actor_name text;
  act text;
  rec_id uuid;
begin
  select full_name into actor_name from public.profiles where id = actor;

  if (tg_op = 'INSERT') then
    act := 'create';
    rec_id := new.id;
  elsif (tg_op = 'UPDATE') then
    act := 'update';
    rec_id := new.id;
  elsif (tg_op = 'DELETE') then
    act := 'delete';
    rec_id := old.id;
  end if;

  insert into public.audit_logs (user_id, user_name, action, module, record_id, description)
  values (
    actor,
    coalesce(actor_name, 'system'),
    act,
    tg_table_name,
    rec_id,
    act || ' on ' || tg_table_name
  );

  if (tg_op = 'DELETE') then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_audit_members on public.members;
create trigger trg_audit_members after insert or update or delete on public.members for each row execute function public.write_audit_log();

drop trigger if exists trg_audit_ministries on public.ministries;
create trigger trg_audit_ministries after insert or update or delete on public.ministries for each row execute function public.write_audit_log();

drop trigger if exists trg_audit_events on public.events;
create trigger trg_audit_events after insert or update or delete on public.events for each row execute function public.write_audit_log();

drop trigger if exists trg_audit_profiles on public.profiles;
create trigger trg_audit_profiles after update on public.profiles for each row execute function public.write_audit_log();

-- =====================================================================
-- 11. ROW LEVEL SECURITY
-- =====================================================================
alter table public.profiles enable row level security;
alter table public.ministries enable row level security;
alter table public.members enable row level security;
alter table public.ministry_members enable row level security;
alter table public.events enable row level security;
alter table public.attendance enable row level security;
alter table public.announcements enable row level security;
alter table public.audit_logs enable row level security;

-- ---- PROFILES ----
drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin" on public.profiles
  for select using (auth.uid() = id or public.is_admin());

drop policy if exists "profiles_update_own_or_admin" on public.profiles;
create policy "profiles_update_own_or_admin" on public.profiles
  for update using (auth.uid() = id or public.is_admin());

drop policy if exists "profiles_insert_admin" on public.profiles;
create policy "profiles_insert_admin" on public.profiles
  for insert with check (public.is_admin());

drop policy if exists "profiles_delete_admin" on public.profiles;
create policy "profiles_delete_admin" on public.profiles
  for delete using (public.is_admin());

-- ---- MINISTRIES ----
drop policy if exists "ministries_select_all" on public.ministries;
create policy "ministries_select_all" on public.ministries
  for select using (auth.role() = 'authenticated');

drop policy if exists "ministries_write_admin_secretary" on public.ministries;
create policy "ministries_write_admin_secretary" on public.ministries
  for all using (public.current_role() in ('administrator', 'secretary'))
  with check (public.current_role() in ('administrator', 'secretary'));

drop policy if exists "ministries_update_own_leader" on public.ministries;
create policy "ministries_update_own_leader" on public.ministries
  for update using (leader_id = auth.uid()) with check (leader_id = auth.uid());

-- ---- MEMBERS ----
drop policy if exists "members_select_all_authenticated" on public.members;
create policy "members_select_all_authenticated" on public.members
  for select using (auth.role() = 'authenticated');

drop policy if exists "members_write_admin_secretary" on public.members;
create policy "members_write_admin_secretary" on public.members
  for all using (public.current_role() in ('administrator', 'secretary'))
  with check (public.current_role() in ('administrator', 'secretary'));

drop policy if exists "members_update_ministry_leader" on public.members;
create policy "members_update_ministry_leader" on public.members
  for update using (
    public.current_role() = 'ministry_leader'
    and ministry_id in (select id from public.ministries where leader_id = auth.uid())
  );

-- ---- MINISTRY_MEMBERS ----
drop policy if exists "ministry_members_select_all" on public.ministry_members;
create policy "ministry_members_select_all" on public.ministry_members
  for select using (auth.role() = 'authenticated');

drop policy if exists "ministry_members_write_admin_secretary" on public.ministry_members;
create policy "ministry_members_write_admin_secretary" on public.ministry_members
  for all using (public.current_role() in ('administrator', 'secretary'))
  with check (public.current_role() in ('administrator', 'secretary'));

drop policy if exists "ministry_members_write_leader" on public.ministry_members;
create policy "ministry_members_write_leader" on public.ministry_members
  for all using (
    ministry_id in (select id from public.ministries where leader_id = auth.uid())
  ) with check (
    ministry_id in (select id from public.ministries where leader_id = auth.uid())
  );

-- ---- EVENTS ----
drop policy if exists "events_select_all" on public.events;
create policy "events_select_all" on public.events
  for select using (auth.role() = 'authenticated');

drop policy if exists "events_write_admin_secretary" on public.events;
create policy "events_write_admin_secretary" on public.events
  for all using (public.current_role() in ('administrator', 'secretary'))
  with check (public.current_role() in ('administrator', 'secretary'));

-- ---- ATTENDANCE ----
drop policy if exists "attendance_select_all" on public.attendance;
create policy "attendance_select_all" on public.attendance
  for select using (auth.role() = 'authenticated');

drop policy if exists "attendance_write_admin_secretary" on public.attendance;
create policy "attendance_write_admin_secretary" on public.attendance
  for all using (public.current_role() in ('administrator', 'secretary'))
  with check (public.current_role() in ('administrator', 'secretary'));

drop policy if exists "attendance_write_leader_own_ministry" on public.attendance;
create policy "attendance_write_leader_own_ministry" on public.attendance
  for insert with check (
    public.current_role() = 'ministry_leader'
    and member_id in (
      select mm.member_id from public.ministry_members mm
      join public.ministries m on m.id = mm.ministry_id
      where m.leader_id = auth.uid()
    )
  );

-- ---- ANNOUNCEMENTS ----
drop policy if exists "announcements_select_all" on public.announcements;
create policy "announcements_select_all" on public.announcements
  for select using (auth.role() = 'authenticated');

drop policy if exists "announcements_write_admin_secretary" on public.announcements;
create policy "announcements_write_admin_secretary" on public.announcements
  for all using (public.current_role() in ('administrator', 'secretary'))
  with check (public.current_role() in ('administrator', 'secretary'));

-- ---- AUDIT LOGS ----
drop policy if exists "audit_logs_select_admin_pastor" on public.audit_logs;
create policy "audit_logs_select_admin_pastor" on public.audit_logs
  for select using (public.current_role() in ('administrator', 'pastor'));

-- audit_logs is written only by the SECURITY DEFINER trigger function above,
-- so no insert policy is needed for normal client roles.

-- =====================================================================
-- 12. REALTIME  (guarded so re-adding an already-added table never errors)
-- =====================================================================
do $$ begin
  alter publication supabase_realtime add table public.members;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.ministries;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.attendance;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.events;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.announcements;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.audit_logs;
exception when duplicate_object then null; end $$;

-- =====================================================================
-- 13. STORAGE BUCKETS
-- =====================================================================
insert into storage.buckets (id, name, public)
values
  ('member-images', 'member-images', true),
  ('church-assets', 'church-assets', true),
  ('imports', 'imports', false)
on conflict (id) do nothing;

drop policy if exists "member_images_read" on storage.objects;
create policy "member_images_read" on storage.objects
  for select using (bucket_id = 'member-images');

drop policy if exists "member_images_write" on storage.objects;
create policy "member_images_write" on storage.objects
  for insert with check (
    bucket_id = 'member-images'
    and public.current_role() in ('administrator', 'secretary')
  );

drop policy if exists "member_images_update" on storage.objects;
create policy "member_images_update" on storage.objects
  for update using (
    bucket_id = 'member-images'
    and public.current_role() in ('administrator', 'secretary')
  );

drop policy if exists "member_images_delete" on storage.objects;
create policy "member_images_delete" on storage.objects
  for delete using (
    bucket_id = 'member-images'
    and public.current_role() in ('administrator', 'secretary')
  );

drop policy if exists "church_assets_read" on storage.objects;
create policy "church_assets_read" on storage.objects
  for select using (bucket_id = 'church-assets');

drop policy if exists "church_assets_write" on storage.objects;
create policy "church_assets_write" on storage.objects
  for insert with check (
    bucket_id = 'church-assets'
    and public.current_role() in ('administrator', 'secretary')
  );

drop policy if exists "imports_admin_secretary_only" on storage.objects;
create policy "imports_admin_secretary_only" on storage.objects
  for all using (
    bucket_id = 'imports'
    and public.current_role() in ('administrator', 'secretary')
  ) with check (
    bucket_id = 'imports'
    and public.current_role() in ('administrator', 'secretary')
  );

-- =====================================================================
-- 14. FIRST ADMINISTRATOR
-- =====================================================================
-- After creating your first user in Supabase Studio → Authentication →
-- Users, run this once (replace the email) to promote them to admin:
--
-- update public.profiles set role = 'administrator' where email = 'you@example.com';
-- =====================================================================
-- =====================================================================
-- 15. MINISTRY LOGOS
-- =====================================================================
alter table public.ministries add column if not exists logo_url text;

-- =====================================================================
-- 16. QR CODE ATTENDANCE (self check-in)
-- =====================================================================
-- A "check-in session" is created by an admin/secretary for a specific
-- service/event. Its token is encoded into a QR code. Anyone who scans
-- it (no login required) lands on a public page, finds their name, and
-- taps "I'm here" — which writes straight into the same `attendance`
-- table your existing Attendance page already reads in real time, so
-- their check-in appears in the CMS instantly.

create table if not exists public.checkin_sessions (
  id uuid primary key default uuid_generate_v4(),
  token text not null unique default replace(uuid_generate_v4()::text, '-', ''),
  attendance_type attendance_type not null,
  event_id uuid references public.events(id) on delete cascade,
  service_date date not null default current_date,
  is_active boolean not null default true,
  expires_at timestamptz,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

alter table public.checkin_sessions enable row level security;

-- Only admins/secretaries manage sessions directly. The public never
-- talks to this table directly — only through the functions below,
-- which run with elevated privileges but only expose what's needed.
drop policy if exists "checkin_sessions_admin_secretary" on public.checkin_sessions;
create policy "checkin_sessions_admin_secretary" on public.checkin_sessions
  for all using (public.current_role() in ('administrator', 'secretary'))
  with check (public.current_role() in ('administrator', 'secretary'));

do $$ begin
  alter publication supabase_realtime add table public.checkin_sessions;
exception when duplicate_object then null; end $$;

-- ---- Public function 1: validate a token and show what it's for ----
create or replace function public.get_checkin_session(p_token text)
returns table (
  attendance_type attendance_type,
  service_date date,
  event_title text,
  valid boolean
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  return query
  select cs.attendance_type, cs.service_date, e.title,
    (cs.is_active and (cs.expires_at is null or cs.expires_at > now()))
  from public.checkin_sessions cs
  left join public.events e on e.id = cs.event_id
  where cs.token = p_token;
end;
$$;

-- ---- Public function 2: search active members by name (token-gated) ----
create or replace function public.search_checkin_members(p_token text, p_query text)
returns table (id uuid, first_name text, last_name text, member_code text)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not exists (
    select 1 from public.checkin_sessions cs
    where cs.token = p_token and cs.is_active and (cs.expires_at is null or cs.expires_at > now())
  ) then
    return; -- no active session for this token: return no results
  end if;

  return query
  select m.id, m.first_name, m.last_name, m.member_code
  from public.members m
  where m.is_archived = false
    and m.status = 'active'
    and (p_query = '' or (m.first_name || ' ' || m.last_name) ilike '%' || p_query || '%')
  order by m.last_name, m.first_name
  limit 15;
end;
$$;

-- ---- Public function 3: record the self check-in ----
create or replace function public.self_check_in(p_token text, p_member_id uuid)
returns table (success boolean, message text)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  session_row public.checkin_sessions;
  already_checked_in boolean;
begin
  select * into session_row
  from public.checkin_sessions cs
  where cs.token = p_token and cs.is_active and (cs.expires_at is null or cs.expires_at > now());

  if not found then
    return query select false, 'This check-in link is no longer active. Please ask for a new QR code.';
    return;
  end if;

  select exists (
    select 1 from public.attendance a
    where a.member_id = p_member_id
      and a.attendance_type = session_row.attendance_type
      and a.service_date = session_row.service_date
      and a.event_id is not distinct from session_row.event_id
  ) into already_checked_in;

  if already_checked_in then
    return query select true, 'You are already checked in. God bless!';
    return;
  end if;

  insert into public.attendance (member_id, attendance_type, event_id, service_date, check_in_time)
  values (p_member_id, session_row.attendance_type, session_row.event_id, session_row.service_date, now());

  return query select true, 'You are checked in. God bless!';
end;
$$;

grant execute on function public.get_checkin_session(text) to anon, authenticated;
grant execute on function public.search_checkin_members(text, text) to anon, authenticated;
grant execute on function public.self_check_in(text, uuid) to anon, authenticated;

-- =====================================================================
-- 17. SMS FUNCTIONALITY (Arkesel Integration)
-- =====================================================================
-- Track all SMS sent through the system for auditing and history

do $$ begin
  create type sms_status as enum ('pending', 'sent', 'failed', 'cancelled');
exception when duplicate_object then null; end $$;

do $$ begin
  create type sms_type as enum ('event_notification', 'event_reminder', 'announcement', 'manual');
exception when duplicate_object then null; end $$;

-- SMS Logs: records of all SMS sent or attempted
create table if not exists public.sms_logs (
  id uuid primary key default uuid_generate_v4(),
  type sms_type not null,
  status sms_status not null default 'pending',
  
  -- Reference to related entities
  event_id uuid references public.events(id) on delete set null,
  announcement_id uuid references public.announcements(id) on delete set null,
  
  -- SMS content and delivery
  message text not null,
  recipient_count integer not null default 0,
  successful_count integer not null default 0,
  failed_count integer not null default 0,
  
  -- Arkesel response
  arkesel_response jsonb,
  error_message text,
  
  -- Metadata
  sent_by uuid references public.profiles(id),
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_sms_logs_type on public.sms_logs (type);
create index if not exists idx_sms_logs_status on public.sms_logs (status);
create index if not exists idx_sms_logs_event on public.sms_logs (event_id);
create index if not exists idx_sms_logs_announcement on public.sms_logs (announcement_id);
create index if not exists idx_sms_logs_created_at on public.sms_logs (created_at desc);

-- SMS Recipients: individual recipients for each SMS batch
create table if not exists public.sms_recipients (
  id uuid primary key default uuid_generate_v4(),
  sms_log_id uuid not null references public.sms_logs(id) on delete cascade,
  member_id uuid not null references public.members(id) on delete cascade,
  phone_number text not null,
  status sms_status not null default 'pending',
  arkesel_message_id text,
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_sms_recipients_log on public.sms_recipients (sms_log_id);
create index if not exists idx_sms_recipients_member on public.sms_recipients (member_id);
create index if not exists idx_sms_recipients_status on public.sms_recipients (status);

-- Scheduled SMS: for automatic reminders (e.g., 24 hours before event)
create table if not exists public.scheduled_sms (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references public.events(id) on delete cascade,
  message text not null,
  scheduled_for timestamptz not null,
  status sms_status not null default 'pending',
  
  -- Member filters (JSON for flexibility)
  recipient_filters jsonb, -- e.g., {"ministry_id": "uuid", "all_members": true}
  
  -- Metadata
  created_by uuid references public.profiles(id),
  sent_at timestamptz,
  sms_log_id uuid references public.sms_logs(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_scheduled_sms_event on public.scheduled_sms (event_id);
create index if not exists idx_scheduled_sms_scheduled_for on public.scheduled_sms (scheduled_for);
create index if not exists idx_scheduled_sms_status on public.scheduled_sms (status);

-- ---- ROW LEVEL SECURITY FOR SMS TABLES ----
alter table public.sms_logs enable row level security;
alter table public.sms_recipients enable row level security;
alter table public.scheduled_sms enable row level security;

-- SMS Logs: admin and secretary can view all
drop policy if exists "sms_logs_select_admin_secretary" on public.sms_logs;
create policy "sms_logs_select_admin_secretary" on public.sms_logs
  for select using (public.current_role() in ('administrator', 'secretary'));

drop policy if exists "sms_logs_insert_admin_secretary" on public.sms_logs;
create policy "sms_logs_insert_admin_secretary" on public.sms_logs
  for insert with check (public.current_role() in ('administrator', 'secretary'));

drop policy if exists "sms_logs_update_admin_secretary" on public.sms_logs;
create policy "sms_logs_update_admin_secretary" on public.sms_logs
  for update using (public.current_role() in ('administrator', 'secretary'));

-- SMS Recipients: admin and secretary can view all
drop policy if exists "sms_recipients_select_admin_secretary" on public.sms_recipients;
create policy "sms_recipients_select_admin_secretary" on public.sms_recipients
  for select using (public.current_role() in ('administrator', 'secretary'));

drop policy if exists "sms_recipients_insert_admin_secretary" on public.sms_recipients;
create policy "sms_recipients_insert_admin_secretary" on public.sms_recipients
  for insert with check (public.current_role() in ('administrator', 'secretary'));

drop policy if exists "sms_recipients_update_admin_secretary" on public.sms_recipients;
create policy "sms_recipients_update_admin_secretary" on public.sms_recipients
  for update using (public.current_role() in ('administrator', 'secretary'));

-- Scheduled SMS: admin and secretary can manage
drop policy if exists "scheduled_sms_admin_secretary" on public.scheduled_sms;
create policy "scheduled_sms_admin_secretary" on public.scheduled_sms
  for all using (public.current_role() in ('administrator', 'secretary'))
  with check (public.current_role() in ('administrator', 'secretary'));

-- Add scheduled_sms to realtime
do $$ begin
  alter publication supabase_realtime add table public.sms_logs;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.scheduled_sms;
exception when duplicate_object then null; end $$;

-- Trigger for scheduled_sms updated_at
drop trigger if exists trg_scheduled_sms_updated_at on public.scheduled_sms;
create trigger trg_scheduled_sms_updated_at before update on public.scheduled_sms for each row execute function public.set_updated_at();
